### PR TITLE
define 'raw_sample_filter' before use

### PR DESCRIPTION
**Pull request by ZhengguoTan**
Dear fastMRI developers,

Please consider whether this commit is necessary. 

I look forward to contributing to this project.

Best Regards,
Zhengguo Tan

### CODE REVIEW

**Review by mmuckley — CHANGES_REQUESTED** [review]
Thanks for bringing this up. I think it needs a small tweak - the `else` branch needs to be able to handle validation or test data partitions.

**Comment by ZhengguoTan** [comment]
> 

Dear @mmuckley, thank you for your quick feedback. To my understanding, the test data partitions are already given in the `if` condition. Or may you be more specific what changes are needed?

Best Regards,
Zhengguo

**Comment by mmuckley** [comment]
Hello @ZhengguoTan, the `if` statement covers if it's a test or challenge split *and* `test_path` is not none. So even if that check fails, the split could still be `"val"`, `"test"` or `"challenge"`. For example, when the test path is in the primary fastMRI data folder and the user does not need to specify `test_path`.

**Comment by mmuckley** [comment]
Closing due to inactivity and should have been fixed by 37ffc89309c941f00ac873f5dd9b6f537411cb10.

**Pull request closed without merging**
